---
- hosts: production
  vars:
    foo: 12345
  remote_user: appadmin
  tasks:
  - name: Copy projects to remote server
    copy: src=../../skeleton-api dest=/var/www/projects/api force=true owner=appadmin